default_server_metrics = ["memory_usage", "ping", "disk_usage", "uptime", "cpu_usage"]

[groundwave]
username = "groundwave"
collectors = ["default_server_metrics"]

[node]
username = "root"
collectors = ["default_server_metrics"]

[localhost]
username = "ubuntu"
collectors = ["default_server_metrics","days_left_to_tg"]

[nsdp]
username = "debian"
collectors = ["default_server_metrics"]
